server:
  port: 8600
spring:
  application:
    name: schedule-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: thw
    password: thw19971017thw
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    tomcat:
      max-wait: 10000
      min-idle: 20
      max-idle: 100
      max-active: 300
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
  activiti:
    database-schema: update
    check-process-definitions: false
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
